import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by crate next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="m-4">
          <h1 className="text-3xl font-bold text-red-500 underline">
            Hello world!
          </h1>
        </div>
      </main>
    </div>
  );
};

export default Home;
